site_name: PopGen.jl
site_description: Population genetics in Julia
site_author: Pavel Dimens and Jason Selwyn
theme:
  name: 'material'
  logo: img/favicon.ico
  favicon : 'img/favicon.ico'
  palette:
    primary: grey
    secondary: blue
    
repo_url: https://github.com/pdimens/PopGen.jl

nav:
- Home: index.md
- Docs "Guide": aboutdocs.md
- Installing: install.md
- The PopObj: popobj.md
- Importing Data: importing.md
- Viewing Data: viewing.md
- Editing PopObj: editing.md
- Plotting: plotting.md
- Contributing: contr.md


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false