site_name: PopGen.jl
site_description: Population genetics in Julia
site_author: Pavel Dimens and Jason Selwyn
copyright: 2019 Pavel Dimens and Jason Selwyn

theme:
  name: 'material'
  logo: img/logo_icon.png
  favicon : 'img/favicon.ico'
  palette:
    primary: green
    secondary: blue

repo_url: https://github.com/pdimens/PopGen.jl
repo_name: PopGen.jl

nav:
- Home: index.md
- Getting started: 
    A Julia primer: juliaprimer.md
    Benchmarks: comparison.md
    How to Install: install.md
    The PopGen 'PopObj':
        What's a PopObj: popobj_type.md
        Accessing parts of a PopObj: PopObj_accessing.md
- Importing Data:
    - Example Data: example_data.md
    - Reading in Data: file_import.md
    - Delimited: delimited.md
    - Genepop: genepop.md
    - VCF: vcf.md
- Manipulating a PopObj: commands.md
- Types of Analyses:
    - Hardy-Weinberg Equilibrium: hardyweinberg.md
    - Relatedness: relatedness.md
- Other:
    Community: community.md
    Development:
        Under the hood functions: hidden_api.md
    Logo Graveyard: logo_graveyard.md


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
