site_name: PopGen.jl
site_description: Population genetics in Julia
site_author: Pavel Dimens and Jason Selwyn
theme:
  name: 'material'
  logo: img/favicon.ico
  favicon : 'img/favicon.ico'
  palette:
    primary: grey
    secondary: blue
    
repo_url: https://github.com/pdimens/PopGen.jl

nav:
- Home: index.md
- Getting started: juliaprimer.md
- Installing: install.md
- The PopObj type:
    - What's a PopObj: popobj_type.md
    - Accessing: PopObj_accessing.md
    - Location data: popobj_location.md
- Importing Data: 
    - CSV and delimited: delimited.md
    - Genepop: genepop.md
    - VCF: vcf.md
- View/edit PopObj: commands.md
- Example data: examples.md
- Community: community.md


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde