name: PopGenCore Upstream
on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - Upstream
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.6'
          - '1.7'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Install PopGen
        uses: julia-actions/julia-buildpkg@latest
      - name: Upstream tests
        shell: julia --color=yes
        run: |
          using Pkg
          try
            # force it to use this PR's version of the package
            Pkg.develop(PackageSpec(path="."))  # resolver may fail with main deps
            Pkg.add(url="https://github.com/BioJulia/PopGenCore.jl", rev = "dev")
            Pkg.add("Test")
            Pkg.update()
            Pkg.test()  # resolver may fail with test time deps
          catch err
            err isa Pkg.Resolve.ResolverError || rethrow()
            # If we can't resolve that means this is incompatible by SemVer and this is fine.
            # It means we marked this as a breaking change, so we don't need to worry about.
            # Mistakenly introducing a breaking change, as we have intentionally made one.
            @info "Not compatible with this release. No problem." exception=err
            exit(0)  # Exit immediately, as a success
          end

#        run: |
#          julia --color=yes -e 'import Pkg; Pkg.add(url="https://github.com/BioJulia/PopGenCore.jl", rev = "dev")'
#          julia --color=yes -e 'import Pkg; Pkg.add("Test")'
#      - name: Run tests
#        uses: julia-actions/julia-runtest@latest